# Generated by Django 3.0 on 2020-07-05 17:36

from django.db import migrations

DEFAULT_CLASSES_TYPES = (
    ('Full Cycle e Estudo de caso', '29/06'),
    ('Microsserviço de assinaturas com RabbitMQ e Golang Buffalo', '30/06'),
    ('Serverless framework e processamento de pagamentos', '01/07'),
    ('Multi-tenancy applications com Django', '02/07'),
    ('Ecommerce com Nest.js, Loopback e ElasticSearch', '03/07'),
    ('Microsserviços com Docker e Kubernetes', '04/07')
)

def add_class_types(apps, schema_editor):
    Aula = apps.get_model('app', 'Aula')

    for name, date in DEFAULT_CLASSES_TYPES:
        aula = Aula(name=name, date=date)
        aula.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    # No database changes; adds choices to action_flag.
    operations = [
        migrations.RunPython(add_class_types),
    ]
